name: Run Benzin Parser

on:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      # Шаг 1: Получение репозитория
      - name: Checkout repository
        uses: actions/checkout@v3

      # Шаг 2: Настройка Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      # Шаг 3: Установка зависимостей
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Шаг 4: Установка Google Chrome и ChromeDriver
      - name: Install Chrome and ChromeDriver
        run: |
          # Установка зависимостей для Google Chrome
          sudo apt-get update
          sudo apt-get install -y \
            wget \
            curl \
            unzip \
            ca-certificates \
            libx11-dev \
            libx11-xcb-dev \
            libxcomposite-dev \
            libxrandr-dev \
            libxrender-dev \
            libxi-dev \
            libxtst-dev \
            libnss3 \
            libgdk-pixbuf2.0-dev \
            libatk-bridge2.0-dev \
            libatk1.0-dev \
            libappindicator3-1 \
            libasound2 \
            libdbus-1-dev \
            libgdk-pixbuf2.0-dev \
            libnspr4-dev \
            libxss1

          # Установка Chromium с вашего источника
          wget https://pkg.freebsd.org/FreeBSD:13:amd64/latest/All/linux-chrome-131.0.6778.85.pkg -O chromium-linux-package.pkg
          sudo dpkg -i chromium-linux-package.pkg
          sudo apt-get install -f

          # Установка ChromeDriver
          wget https://storage.googleapis.com/chrome-for-testing-public/131.0.6778.85/linux64/chromedriver-linux64.zip
          unzip chromedriver-linux64.zip
          sudo mv chromedriver /usr/local/bin/

      # Шаг 5: Запуск парсера
      - name: Run benzin.py
        run: python benzin.py
