name: Deploy to Render (Linux Server)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. Клонируем репозиторий
    - name: Checkout repository
      uses: actions/checkout@v3

    # 2. Скачиваем и устанавливаем Chromium и ChromeDriver
    - name: Install Chromium and set up ChromeDriver
      run: |
        sudo apt-get update
        sudo apt-get install -y wget unzip build-essential python3-dev \
          curl git libnss3-dev libx11-dev libxcomposite-dev \
          libxrandr-dev libgdk-pixbuf2.0-dev libatk-bridge2.0-dev \
          libatk1.0-dev libcups2-dev libasound2-dev \
          libdbus-1-dev libxtst-dev

        # Скачиваем и устанавливаем Chromium из правильного пакета
        wget https://pkg.freebsd.org/FreeBSD:13:amd64/latest/All/linux-chrome-131.0.6778.85.pkg -O chromium-linux-package.pkg
        sudo apt-get install -y chromium-browser

        # Устанавливаем ChromeDriver для версии 131.0.6778.85
        CHROMEDRIVER_URL="https://storage.googleapis.com/chrome-for-testing-public/131.0.6778.85/linux64/chromedriver-linux64.zip"
        wget $CHROMEDRIVER_URL -O chromedriver-linux64.zip

        # Распаковываем архив
        unzip chromedriver-linux64.zip -d chromedriver-linux64

        # Перемещаем файл chromedriver в /usr/local/bin
        sudo mv chromedriver-linux64/chromedriver-linux64/chromedriver /usr/local/bin/chromedriver

        # Проверяем версию ChromeDriver
        chromedriver --version

    # 3. Устанавливаем Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    # 4. Устанавливаем зависимости Python
    - name: Install Python dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install --upgrade pip
        pip install -r requirements.txt

    # 5. Тестируем Selenium в headless режиме
    - name: Test Selenium in headless mode
      run: |
        source venv/bin/activate
        python -c "
        from selenium import webdriver;
        from selenium.webdriver.chrome.service import Service;
        from selenium.webdriver.chrome.options import Options;

        # Настройка параметров для headless режима
        options = Options();
        options.binary_location = '/usr/bin/chromium-browser';  # Путь к установленному Chromium
        options.add_argument('--headless');
        options.add_argument('--no-sandbox');
        options.add_argument('--disable-dev-shm-usage');
        options.add_argument('--remote-debugging-port=9222');  # Устанавливаем порт для DevTools
        options.add_argument('--disable-software-rasterizer');  # Отключаем использование софтварного рендеринга

        # Путь к ChromeDriver
        service = Service('/usr/local/bin/chromedriver');
        driver = webdriver.Chrome(service=service, options=options);

        # Тестируем подключение
        driver.get('https://www.google.com');
        print('Page title is:', driver.title);
        driver.quit();
        "
        which chromium-browser
        which chromedriver
