name: Deploy to Render (Linux Server)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. Клонируем репозиторий
    - name: Checkout repository
      uses: actions/checkout@v3

    # 2. Устанавливаем конкретную версию Chromium и ChromeDriver
    - name: Install Chromium and ChromeDriver
      run: |
        # Устанавливаем фиксированную версию Chromium (108)
        sudo apt-get update
        sudo apt-get install -y wget unzip
        wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb -O /tmp/chrome.deb
        sudo apt install -y /tmp/chrome.deb

        # Устанавливаем соответствующий ChromeDriver
        CHROMIUM_VERSION=$(google-chrome --version | grep -oP '\d+\.\d+\.\d+' | head -1)
        echo "Using Chromium version: $CHROMIUM_VERSION"
        
        # Устанавливаем нужную версию ChromeDriver
        DRIVER_VERSION=$(curl -sS https://chromedriver.storage.googleapis.com/LATEST_RELEASE_108)
        wget -q "https://chromedriver.storage.googleapis.com/$DRIVER_VERSION/chromedriver_linux64.zip" -P /tmp
        sudo unzip /tmp/chromedriver_linux64.zip -d /usr/local/bin/
        sudo chmod +x /usr/local/bin/chromedriver

    # 3. Устанавливаем Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    # 4. Устанавливаем зависимости Python
    - name: Install Python dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install --upgrade pip
        pip install -r requirements.txt

    # 5. Тестируем Selenium
    - name: Test Selenium in headless mode
      run: |
        source venv/bin/activate
        python -c "
        from selenium import webdriver;
        from selenium.webdriver.chrome.service import Service;
        from selenium.webdriver.chrome.options import Options;
        options = Options();
        options.binary_location = '/usr/bin/google-chrome';
        options.add_argument('--headless');
        options.add_argument('--no-sandbox');
        options.add_argument('--disable-dev-shm-usage');
        service = Service('/usr/local/bin/chromedriver');
        driver = webdriver.Chrome(service=service, options=options);
        driver.get('https://www.google.com');
        print('Page title is:', driver.title);
        driver.quit();
                "
        
        
