name: Deploy Flask App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        # Устанавливаем virtualenv (если не установлен)
        sudo pip install virtualenv
        
        # Создаем новое виртуальное окружение
        virtualenv venv
        
        # Активируем виртуальное окружение
        source venv/bin/activate
        
        # Устанавливаем зависимости
        pip install -r requirements.txt

        # 1. Обновляем pip до последней версии
        sudo python3 -m pip install --upgrade pip
        
        # 3. Обновляем selenium и webdriver-manager
        sudo pip install --upgrade selenium webdriver-manager
        
        # 4. Устанавливаем Google Chrome и необходимые библиотеки
        sudo apt update
        sudo apt install -y google-chrome-stable libx11-xcb1 libnss3 libasound2
        
        # 5. Проверяем, что Google Chrome установлен
        google-chrome --version
        
        # 6. Проверяем доступность и содержимое директории /var/lib/apt/lists/
        ls -l /var/lib/apt/lists/
        
        # 7. Удаляем блокировки APT (если они возникли)
        sudo rm /var/lib/apt/lists/lock
        sudo rm /var/cache/apt/pkgcache.bin
        sudo rm /var/cache/apt/srcpkgcache.bin
        
        # 8. Даем права на каталоги для apt
        sudo chmod -R 755 /var/lib/apt/lists/
        sudo apt upgrade








