name: Deploy Flask App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        sudo python -m pip install --upgrade pip
        sudo pip install -r requirements.txt
        sudo pip install --upgrade selenium webdriver-manager
        sudo apt update
        sudo apt install -y google-chrome-stable
        sudo rm -rf ~/.wdm
        sudo apt-get update && apt-get install -y google-chrome-stable libx11-xcb1 libnss3 libasound2
        sudo google-chrome --version
        ls -l /var/lib/apt/lists/
        sudo rm /var/lib/apt/lists/lock
        sudo rm /var/cache/apt/pkgcache.bin
        sudo rm /var/cache/apt/srcpkgcache.bin
        sudo apt-get update
        sudo chmod -R 755 /var/lib/apt/lists/






