name: Deploy to Render (Linux Server)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. Клонируем репозиторий
    - name: Checkout repository
      uses: actions/checkout@v3
    # 2. Устанавливаем Chromium и настраиваем ChromeDriver
    - name: Install Chromium and set up ChromeDriver
      run: |
        sudo apt-get update
        sudo apt-get install -y wget unzip
    
        # Устанавливаем Chromium
        sudo apt-get install -y chromium-browser
    
        # Получаем версию установленного Chromium
        CHROMIUM_VERSION=$(chromium-browser --version | awk '{print $2}' | cut -d'.' -f1,2)
    
        echo "Installing ChromeDriver for Chromium version: $CHROMIUM_VERSION"
    
        # Загружаем ChromeDriver для версии 131.0.6778.87
        CHROMEDRIVER_URL="https://storage.googleapis.com/chrome-for-testing-public/131.0.6778.87/linux64/chromedriver-linux64.zip"
        wget $CHROMEDRIVER_URL -O chromedriver-linux64.zip
    
        # Распаковываем архив
        unzip chromedriver-linux64.zip -d chromedriver-linux64
    
        # Перемещаем файл chromedriver в /usr/local/bin
        sudo mv chromedriver-linux64/chromedriver-linux64/chromedriver /usr/local/bin/chromedriver
    
        # Проверяем версию ChromeDriver
        chromedriver --version

    
    # 3. Устанавливаем Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    # 4. Устанавливаем зависимости Python
    - name: Install Python dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install --upgrade pip
        pip install -r requirements.txt

    # 5. Тестируем Selenium в headless режиме
    - name: Test Selenium in headless mode
      run: |
        source venv/bin/activate
        python -c "
        from selenium import webdriver;
        from selenium.webdriver.chrome.service import Service;
        from selenium.webdriver.chrome.options import Options;

        # Настройки ChromeDriver
        options = Options();
        options.binary_location = '/usr/bin/chromium-browser';
        options.add_argument('--headless');
        options.add_argument('--no-sandbox');
        options.add_argument('--disable-dev-shm-usage');

        # Настраиваем драйвер
        service = Service('/usr/local/bin/chromedriver');
        driver = webdriver.Chrome(service=service, options=options);

        # Тестируем доступ к странице
        driver.get('https://www.google.com');
        print('Page title is:', driver.title);
        driver.quit();
        "
