name: Deploy to Render (Linux Server)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. Клонируем репозиторий
    - name: Checkout repository
      uses: actions/checkout@v3

    # 2. Устанавливаем Chromium
    - name: Install Chromium
      run: |
        sudo apt-get update -y
        sudo apt-get install -y chromium-browser

    # 3. Устанавливаем ChromeDriver (с фиксом версии)
    - name: Install ChromeDriver
      run: |
        # Получаем версию Chromium
        CHROMIUM_VERSION=$(chromium-browser --version | grep -oP '\d+\.\d+\.\d+')
        CHROMIUM_MAJOR_VERSION=$(echo $CHROMIUM_VERSION | cut -d '.' -f 1)
        
        # Проверяем доступность подходящей версии ChromeDriver
        DRIVER_VERSION=$(curl -sS https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROMIUM_MAJOR_VERSION)
        echo "Detected ChromeDriver version: $DRIVER_VERSION"

        # Скачиваем соответствующий ChromeDriver
        wget -q "https://chromedriver.storage.googleapis.com/$DRIVER_VERSION/chromedriver_linux64.zip" -P /tmp

        # Устанавливаем ChromeDriver
        sudo unzip /tmp/chromedriver_linux64.zip -d /usr/local/bin/
        sudo chmod +x /usr/local/bin/chromedriver

    # 4. Устанавливаем Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    # 5. Устанавливаем зависимости Python
    - name: Install Python dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install --upgrade pip
        pip install -r requirements.txt

    # 6. Тестируем Selenium
    - name: Test Selenium in headless mode
      run: |
        source venv/bin/activate
        python -c "
        from selenium import webdriver;
        from selenium.webdriver.chrome.service import Service;
        from selenium.webdriver.chrome.options import Options;
        options = Options();
        options.binary_location = '/usr/bin/chromium-browser';
        options.add_argument('--headless');
        options.add_argument('--no-sandbox');
        options.add_argument('--disable-dev-shm-usage');
        service = Service('/usr/local/bin/chromedriver');
        driver = webdriver.Chrome(service=service, options=options);
        driver.get('https://www.google.com');
        print('Page title is:', driver.title);
        driver.quit();
                "
