name: Deploy to Render (Linux Server)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. Клонируем репозиторий
    - name: Checkout repository
      uses: actions/checkout@v3

    # 2. Скачиваем и собираем Chromium из исходников
    - name: Download and build Chromium from source
      run: |
        sudo apt-get update
        sudo apt-get install -y wget unzip build-essential python3-dev \
          curl git libnss3-dev libx11-dev libxcomposite-dev \
          libxrandr-dev libgdk-pixbuf2.0-dev libatk-bridge2.0-dev \
          libatk1.0-dev libcups2-dev libasound2-dev \
          libdbus-1-dev libxtst-dev

        # Скачиваем архив с исходным кодом Chromium
        wget https://chromium.googlesource.com/chromium/src/+archive/refs/tags/131.0.6778.85.tar.gz -O chromium-src.tar.gz

        # Распаковываем архив
        tar -xvzf chromium-src.tar.gz
        cd src

        # Устанавливаем необходимые зависимости для сборки Chromium
        ./build/install-build-deps.sh

        # Сборка Chromium (можно указать конкретный профиль сборки, чтобы ускорить процесс)
        ./build/gyp_chromium
        make -j$(nproc) chromium

        # Сохраняем собранный Chromium
        sudo cp out/Release/chrome /usr/bin/chromium-browser

    # 3. Загружаем и устанавливаем ChromeDriver
    - name: Install ChromeDriver
      run: |
        # Устанавливаем версию Chromium
        CHROMIUM_VERSION=$(chromium-browser --version | awk '{print $2}' | cut -d'.' -f1,2)
        echo "Chromium version: $CHROMIUM_VERSION"

        # Загружаем нужную версию ChromeDriver для соответствующей версии Chromium
        CHROMEDRIVER_VERSION="131.0.6778.85"
        CHROMEDRIVER_URL="https://storage.googleapis.com/chrome-for-testing-public/$CHROMEDRIVER_VERSION/linux64/chromedriver-linux64.zip"
        wget $CHROMEDRIVER_URL -O chromedriver-linux64.zip

        # Распаковываем архив с ChromeDriver
        unzip chromedriver-linux64.zip -d chromedriver-linux64

        # Перемещаем файл chromedriver в /usr/local/bin
        sudo mv chromedriver-linux64/chromedriver-linux64/chromedriver /usr/local/bin/chromedriver

        # Проверяем установленную версию ChromeDriver
        chromedriver --version

    # 4. Устанавливаем Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    # 5. Устанавливаем зависимости Python
    - name: Install Python dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install --upgrade pip
        pip install -r requirements.txt

    # 6. Тестируем Selenium в headless режиме
    - name: Test Selenium in headless mode
      run: |
        source venv/bin/activate
        python -c "
        from selenium import webdriver;
        from selenium.webdriver.chrome.service import Service;
        from selenium.webdriver.chrome.options import Options;

        # Настройка параметров для headless режима
        options = Options();
        options.binary_location = '/usr/bin/chromium-browser';  # Путь к установленному Chromium
        options.add_argument('--headless');
        options.add_argument('--no-sandbox');
        options.add_argument('--disable-dev-shm-usage');
        options.add_argument('--remote-debugging-port=9222');  # Устанавливаем порт для DevTools
        options.add_argument('--disable-software-rasterizer');  # Отключаем использование софтварного рендеринга

        # Путь к ChromeDriver
        service = Service('/usr/local/bin/chromedriver');
        driver = webdriver.Chrome(service=service, options=options);

        # Тестируем подключение
        driver.get('https://www.google.com');
        print('Page title is:', driver.title);
        driver.quit();
        "
        which chromium-browser
        which chromedriver
